#!/bin/bash

clear

echo "+-----------------------------------------+"
echo "|                                         |"
echo -e "| Willkommen zum Download des \e[94mPi Control\e[0m! |"
echo "|                                         |"
echo "|        -------------------------        |"
echo "|                                         |"
echo "| Version: 1.3.3                          |"
echo "|                                         |"
echo "| Weitere Informationen zum Pi Control    |"
echo "| findest du auf meinem Blog unter:       |"
echo "| http://willy-tech.de                    |"
echo "|                                         |"
echo "| Oder auf der offiziellen Pi Control     |"
echo "| Seite unter: https://pi-control.de      |"
echo "|                                         |"
echo "| Bei Fragen oder Problemen schreib mir   |"
echo "| eine E-Mail an: support@willy-tech.de   |"
echo "|                                         |"
echo "+-----------------------------------------+"

selectedWebserver=""
selectedWebserverPath=""
inputJNWebserver=""
picontrolFolder=""

echo ""

PS3=$(echo -e "\e[1mBitte waehle deinen Webserver aus: \e[0m")
options="Apache2 Nginx Lighttpd Sonstiges"
select opt in $options;
do
	if [ "$opt" = "Apache2" ]; then
		selectedWebserver=$opt
		selectedWebserverPath="/var/www/html/"
		break
	elif [ "$opt" = "Nginx" ]; then
		selectedWebserver=$opt
		selectedWebserverPath="/usr/share/nginx/html/"
		break
	elif [ "$opt" = "Lighttpd" ]; then
		selectedWebserver=$opt
		selectedWebserverPath="/var/www/"
		break
	elif [ "$opt" = "Sonstiges" ]; then
		selectedWebserver=$opt
		selectedWebserverPath="/"
		break
	fi
done

if [ ! "$selectedWebserver" = "Sonstiges" ]; then
	while :
	do
		echo ""
		echo "Der standard Pfad zu $selectedWebserver ist \"$selectedWebserverPath\"."
		echo -en "\e[1mIst der Pfad bei dir der gleiche? [j/n]: \e[0m"
		read inputJNWebserver

		if [ "$inputJNWebserver" = "j" ] || [ "$inputJNWebserver" = "J" ]; then
			break
		elif [ "$inputJNWebserver" = "n" ] || [ "$inputJNWebserver" = "N" ]; then
			echo ""
			echo -e "\e[1mBitte gebe den absoluten Pfad zum Webserververzeichnis an:\e[0m"
			read selectedWebserverPath
			break
		fi
	done
fi

if [ ! -d "$selectedWebserverPath" ]; then
	echo ""
	echo -e "\e[91mLeider konnte der Ordner nicht gefunden werden. Bitte wiederhole den Vorgang!"
	exit
fi

hostname=$(cat /proc/sys/kernel/hostname)

echo ""
echo -e "\e[1mUnter welchen Ordner soll das Pi Control spaeter erreichbar sein?"
echo -e "(Z. B. \"pic\" = http://$hostname/pic/ ; Keine Angabe = http://$hostname/)\e[0m"
read picontrolFolder

if [ ! -d "$selectedWebserverPath/$picontrolFolder" ]; then
        mkdir /$selectedWebserverPath/$picontrolFolder
fi

if [ -a "$selectedWebserverPath/$picontrolFolder/index.php" ]; then
	timeDate=$(date +"%Y%m%d%H%M")
	mv "$selectedWebserverPath/$picontrolFolder/index.php" "$selectedWebserverPath/$picontrolFolder/index_$timeDate.php"
	echo ""
	echo -e "\e[91mEs wurde bereis eine index.php im Ordner $selectedWebserverPath/$picontrolFolder gefunden."
	echo -e "Diese wurde, um die Installation des Pi Control zu ermöglichen, umbenannt.\e[0m"
fi

echo ""
echo -n "Pi Control wird heruntergeladen... "

statusCode=$(curl -O -J -L http://goo.gl/gs7BJI -s -o /dev/null -w "%{http_code}")

if [ "$statusCode" = "200" ]; then
	echo -e "\e[92mErfolgreich\e[0m"
else
	echo -e "\e[91mFehler! Statuscode: $statusCode\e[0m"
	echo "Bitte kontaktiere mich, ich werde dir so schnell wie moeglich bei dem Problem behilflich sein."
	exit
fi

echo -n "Pi Control wird entpackt... "

unzipFiles=$(unzip -q -o Pi_Control_-_1.3.3.zip -d /$selectedWebserverPath/$picontrolFolder)

if [ "$unzipFiles" = "" ]; then
        echo -e "\e[92mErfolgreich\e[0m"
else
        echo -e "\e[91mFehler!\e[0m"
	echo "$unzipFiles"
        echo "Bitte kontaktiere mich, ich werde dir so schnell wie moeglich bei dem Problem behilflich sein."
        exit
fi

echo ""
echo "Das Pi Control wurde erfolgreich heruntergeladen und entpackt."
echo "Du kannst nun in deinem Browser mit der Installation fortfahren."
echo -e "Die Installation findest du unter \e[94mhttp://$hostname/$picontrolFolder/\e[0m"
